### ISSUE TITLE
Option to set jsPsych path

### ISSUE THREAD

**Issue by kupiqu** [djnavarro/jaysire#22]
I submitted a [pull request](https://github.com/jspsych/jsPsych/pull/704) to fix this [issue](https://github.com/jspsych/jsPsych/issues/703) in jsPsych (radiobuttons appearing on the right in the survey-multi-choice plugin).

Everything works fine in my end now, but given that jaysire loads its internal version of jsPsych (latest stable), I need to manually replace the survey-multi-choice plugin in jaysire, which is not ideal because it makes the local jaysire repo to diverge from remote/upstream.

I think a better approach would be to allow setting a path for jsPsych and defaulting to current behavior if not passed.

If so, it would probably be good to maintain jsPsych folder structure in jaysire as well, i.e., having its `css` and `plugins` subfolders, because then the only thing that needs changing is the root path to jsPsych.

**Comment by djnavarro** [comment]
closed by #21
